# -*- coding: utf-8 -*-
{
    'name': "Purchase SIIC Customization",
    'summary': """  Custom Application To Purchase SIIC Customization """,
    'description': """ Purchase SIIC Customization  """,
    'author': "SIIC",
    'category': 'Operations/Purchase',
    'depends': ['base', 'portal', 'purchase', 'multi_branch'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/purchase_payment_type.xml',
        'views/purchase_guarantee_type.xml',
        'views/payment_term.xml',
        'views/purchase_delivery_time.xml',
        'views/purchase_order.xml',
        'views/purchase_tender_view.xml',
        'views/purchase_branch_req.xml',
        'views/purchase_tender_order.xml',
        'views/purchase_tender_bidline_view.xml',
        'views/purchase_order_followup.xml',
        'wizard/update_qty_wizard_view.xml',
        'wizard/purchase_order_wizard_view.xml',
        'report/report_purchase_tender_template.xml',
        'report/report_branch_request_template.xml',
        'report/purchase_order_followup_template.xml',
    ],
    'images': ['static/description/icon.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
